### ISSUE TITLE
NPE when using parse API

### ISSUE THREAD

**Issue by lewismc** [kohsah/akomantoso-lib#13]
Hi @kohsah,
I am running into some NPE when parsing the sample document as provided within the [documentation](http://kohsah.github.io/akomantoso-lib/). The document looks as follows
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<akomaNtoso 
  xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06">
  <doc contains="singleVersion" name="test_doc">
    <meta>
      <identification source="#a_source">
        <FRBRWork>
          <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
          <FRBRuri value="/ak/bill/2013-01-01/A1"/>
        </FRBRWork>
      </identification>
      <publication date="2013-01-01" number="42" name="pub" 
          currentId="test_pub"/>
    </meta>
  </doc>
</akomaNtoso>
```
The stacktrace I get when using the parse API is as follows
```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.akomantoso.api.impl.PackageResourceResolver.resolveResource(PackageResourceResolver.java:25)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:109)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1076)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:660)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2052)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1008)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:620)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:575)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:541)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:252)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:627)
	at org.akomantoso.api.AnValidator.validate(AnValidator.java:113)
	at org.akomantoso.api.AnValidator.validate(AnValidator.java:69)
	at org.akomantoso.api.AnParser.parse(AnParser.java:59)
	at org.apache.tika.parser.akn.AkomaNtosoParser.parse(AkomaNtosoParser.java:94)
	at org.apache.tika.parser.akn.AkomaNtosoParserTest.testParseAkomaNtosoMetadata(AkomaNtosoParserTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

```
This is the result of making the following function call
```
      resultDoc = AnParser.parse(vSchema, stream);
```
Any ideas what is up here?

**Comment by lewismc** [comment]
When I parse and Unmarshall manually e.g. not using the parse API all seems to be in order and I am able to retrieve values from the anDoc no problems.

**Comment by lewismc** [comment]
@kohsah are you around the D.C. area and will you be at the AkomaNtoso conference tomorrow?

**Comment by kohsah** [comment]
Hi @lewismc , Just tried simulating this didn't get the exception you are getting ,the file parses successfully (even if its not a valid AN file) . If you check the Unit tests, there is a unit test for Parse (for CSD07... but you can set it to to CSD06 too ). Here is the unit test I used : 
```
    package org.akomantoso;

    import java.io.File;
    import java.io.IOException;
    import junit.framework.TestCase;
    import org.akomantoso.api.AnDocType;
    import org.akomantoso.api.AnParser;
    import org.akomantoso.api.AnVersion;


    public class TestAnParser_CSD06 extends TestCase {

        AnVersion _version = new AnVersion(3, "CSD06");
        // file to parse and discover type
        File _parse  = new File("./src/test/java/testdocs/akomantoso_doc_simple_csd06.xml");    


        public TestAnParser_CSD06(String testName) throws IOException {
            super(testName);
        }

        @Override
        protected void setUp() throws Exception {
            super.setUp();
        }

        @Override
        protected void tearDown() throws Exception {
            super.tearDown();
        }

        /**
         * Test of validate method, of class AnValidator.
         */
        public void testParse() throws Exception {
            System.out.println("parse");
            // file 1 should validate
            AnDocType resultDoc = AnParser.parse(_version, _parse);
            assertEquals(resultDoc.objClass, 
                    "org.akomantoso.schema.v3.csd06.OpenStructure");
            assertEquals(resultDoc.typeName, 
                    "doc");

        }
    }
```

akomantoso_doc_simple_csd06.xml is exactly the file you have above ... 

Could you tell me which particular parse() API you are calling ? The unit test covers only the File handle input file version.  I suspect there may be a bug in one of the other input types ... 

Regarding the IANC conference, no I am not around ... but I will be presenting remotely in the conference in Fairfax ...

**Comment by kohsah** [comment]
Let me test the Stream api ..

**Comment by kohsah** [comment]
OK I got an error when I used the Parse api with InputStream as the input rather than File

**Comment by kohsah** [comment]
Alright found the problem... I validate input before parsing, the stream gets closed by the validator, and so its not usable anymore. Will fix it shortly...

**Comment by lewismc** [comment]
I was going to try and fix this but I can't find where the validator closes the InputStream.

**Comment by kohsah** [comment]
@lewismc I have just committed a fix for the inputStream problem (see https://github.com/kohsah/akomantoso-lib/commit/1136e0383625ced33213f23b485e8ca51f56804e ) The main changes are to org.akomantoso.api.AnParser, I clone the inputstream by writing it out to a bytearray and using that to output an inputstream. There is no explicit close for the stream it gets automatically closed once the stream has been read (in our case by the validator) .  

Note: the problem still persists for the parse() API that uses a Reader, will need to implement a similar cloning mecanism like for the inputstream

**Comment by kohsah** [comment]
Note: The AnParser() class methods are no longer static they are member methods. I had some weird static related issues when I use the library within Jython.

**Comment by kohsah** [comment]
Will clean-up and package into a release ...for now you can build from source

**Comment by lewismc** [comment]
Fantastic @kohsah
