### ISSUE TITLE
Test Failures in master branch 1.0.14-SNAPSHOT

### ISSUE THREAD

**Issue by lewismc** [kohsah/akomantoso-lib#16]
Hi @kohsah when I try mvn test I am getting the following stack traces

```
Running org.akomantoso.TestAnParser_CSD06
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/lmcgibbn/.m2/repository/org/slf4j/slf4j-jdk14/1.7.5/slf4j-jdk14-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/lmcgibbn/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
parse
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.946 sec
Running org.akomantoso.TestAnParser_CSD07
parse
Aug 26, 2015 7:43:07 PM org.akomantoso.api.AnTypeGetterHelper getMethod
INFO: Method : getAmendent was not found
java.lang.NoSuchMethodException: org.akomantoso.schema.v3.csd07.AkomaNtosoType.getAmendent()
    at java.lang.Class.getMethod(Class.java:1670)
    at org.akomantoso.api.AnTypeGetterHelper.getMethod(AnTypeGetterHelper.java:73)
    at org.akomantoso.api.AnTypeGetterHelper.getDocType(AnTypeGetterHelper.java:99)
    at org.akomantoso.api.AnParser.parse(AnParser.java:186)
    at org.akomantoso.api.AnParser.parse(AnParser.java:170)
    at org.akomantoso.TestAnParser_CSD07.testParse(TestAnParser_CSD07.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Aug 26, 2015 7:43:07 PM org.akomantoso.api.AnTypeGetterHelper getMethod
INFO: Method : getAmendentList was not found
java.lang.NoSuchMethodException: org.akomantoso.schema.v3.csd07.AkomaNtosoType.getAmendentList()
    at java.lang.Class.getMethod(Class.java:1670)
    at org.akomantoso.api.AnTypeGetterHelper.getMethod(AnTypeGetterHelper.java:73)
    at org.akomantoso.api.AnTypeGetterHelper.getDocType(AnTypeGetterHelper.java:99)
    at org.akomantoso.api.AnParser.parse(AnParser.java:186)
    at org.akomantoso.api.AnParser.parse(AnParser.java:170)
    at org.akomantoso.TestAnParser_CSD07.testParse(TestAnParser_CSD07.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.004 sec
Running org.akomantoso.TestAnParser_CSD13
parse
Aug 26, 2015 7:43:08 PM org.akomantoso.api.AnTypeGetterHelper getMethod
INFO: Method : getAmendent was not found
java.lang.NoSuchMethodException: org.akomantoso.schema.v3.csd13.AkomaNtosoType.getAmendent()
    at java.lang.Class.getMethod(Class.java:1670)
    at org.akomantoso.api.AnTypeGetterHelper.getMethod(AnTypeGetterHelper.java:73)
    at org.akomantoso.api.AnTypeGetterHelper.getDocType(AnTypeGetterHelper.java:99)
    at org.akomantoso.api.AnParser.parse(AnParser.java:186)
    at org.akomantoso.api.AnParser.parse(AnParser.java:170)
    at org.akomantoso.TestAnParser_CSD13.testParse(TestAnParser_CSD13.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Aug 26, 2015 7:43:08 PM org.akomantoso.api.AnTypeGetterHelper getMethod
INFO: Method : getAmendentList was not found
java.lang.NoSuchMethodException: org.akomantoso.schema.v3.csd13.AkomaNtosoType.getAmendentList()
    at java.lang.Class.getMethod(Class.java:1670)
    at org.akomantoso.api.AnTypeGetterHelper.getMethod(AnTypeGetterHelper.java:73)
    at org.akomantoso.api.AnTypeGetterHelper.getDocType(AnTypeGetterHelper.java:99)
    at org.akomantoso.api.AnParser.parse(AnParser.java:186)
    at org.akomantoso.api.AnParser.parse(AnParser.java:170)
    at org.akomantoso.TestAnParser_CSD13.testParse(TestAnParser_CSD13.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.922 sec
Running org.akomantoso.TestAnUnmarshallAndMarshall_CSD06
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06">
    <doc contains="singleVersion" name="test_doc">
        <meta>
            <identification source="#a_source">
                <FRBRWork>
                    <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
                    <FRBRuri value="/ak/bill/2013-01-01/A1"/>
                </FRBRWork>
            </identification>
            <publication date="2013-01-01" number="42" name="pub" currentId="test_pub"/>
        </meta>
    </doc>
</akomaNtoso>
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.914 sec
Running org.akomantoso.TestAnUnmarshallAndMarshall_CSD07
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD07">
    <doc contains="singleVersion" name="test_doc">
        <meta>
            <identification source="#a_source">
                <FRBRWork>
                    <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
                    <FRBRuri value="/ak/bill/2013-01-01/A1"/>
                </FRBRWork>
            </identification>
            <publication name="pub" date="2013-01-01" number="42" currentId="test_pub"/>
        </meta>
    </doc>
</akomaNtoso>
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.775 sec
Running org.akomantoso.TestAnUnmarshallAndMarshall_CSD13
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD13">
    <doc contains="singleVersion" name="test_doc">
        <meta>
            <identification source="#a_source">
                <FRBRWork>
                    <FRBRthis value="/ak/bill/2013-01-01/A1/memorandum"/>
                    <FRBRuri value="/ak/bill/2013-01-01/A1"/>
                </FRBRWork>
            </identification>
            <publication date="2013-01-01" number="42" name="pub" wId="test_pub"/>
        </meta>
    </doc>
</akomaNtoso>
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.722 sec
Running org.akomantoso.TestAnValidatorTest_CSD06
validate
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.266 sec <<< FAILURE!
testValidate(org.akomantoso.TestAnValidatorTest_CSD06)  Time elapsed: 0.265 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Validation of file succeeded when it should have failed expected:<false> but was:<true>
    at junit.framework.Assert.fail(Assert.java:47)
    at junit.framework.Assert.failNotEquals(Assert.java:282)
    at junit.framework.Assert.assertEquals(Assert.java:64)
    at junit.framework.Assert.assertEquals(Assert.java:149)
    at org.akomantoso.TestAnValidatorTest_CSD06.testValidate(TestAnValidatorTest_CSD06.java:50)

Running org.akomantoso.TestAnValidatorTest_CSD07
validate
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.199 sec <<< FAILURE!
testValidate(org.akomantoso.TestAnValidatorTest_CSD07)  Time elapsed: 0.198 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Validation of file succeeded when it should have failed expected:<false> but was:<true>
    at junit.framework.Assert.fail(Assert.java:47)
    at junit.framework.Assert.failNotEquals(Assert.java:282)
    at junit.framework.Assert.assertEquals(Assert.java:64)
    at junit.framework.Assert.assertEquals(Assert.java:149)
    at org.akomantoso.TestAnValidatorTest_CSD07.testValidate(TestAnValidatorTest_CSD07.java:50)

Running org.akomantoso.TestAnValidatorTest_CSD13
validate
Aug 26, 2015 7:43:11 PM org.akomantoso.api.AnValidator validate
SEVERE: VALIDATION ERROR: Sax Parse error Validation
org.xml.sax.SAXParseException; systemId: file:/usr/local/akomantoso-lib/./src/test/java/testdocs/akomantoso_act_csd13.xml; lineNumber: 40; columnNumber: 100; cvc-complex-type.3.2.2: Attribute 'currentId' is not allowed to appear in element 'componentData'.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:458)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3237)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2714)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2056)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:766)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
    at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
    at javax.xml.validation.Validator.validate(Validator.java:124)
    at org.akomantoso.api.AnValidator.validate(AnValidator.java:117)
    at org.akomantoso.api.AnValidator.validate(AnValidator.java:95)
    at org.akomantoso.TestAnValidatorTest_CSD13.testValidate(TestAnValidatorTest_CSD13.java:49)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
    at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
    at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

error details :
 line : 40, col : 100
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.191 sec

Results :

Failed tests:   testValidate(org.akomantoso.TestAnValidatorTest_CSD06): Validation of file succeeded when it should have failed expected:<false> but was:<true>
  testValidate(org.akomantoso.TestAnValidatorTest_CSD07): Validation of file succeeded when it should have failed expected:<false> but was:<true>

Tests run: 12, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by lewismc** [comment]
Please note that the presence of certain java.lang.NoSuchMethodException: org.akomantoso.schema.v3.csd07.AkomaNtosoType.getAmendent() Exceptions are 'OK'. 
We have to check if the method exists, because the supported doctypes across AN versions may change.
There is an issue here though... which is that both AkomaNtosoType.getAmendent()  and AkomaNtosoType.getAmendentList() do exist in v3.csd07 and v3.csd13!

**Comment by lewismc** [comment]
@kohsah which characteristics of the documents used within the unit tests determine that [the former assertion should validate](https://github.com/kohsah/akomantoso-lib/blob/master/src/test/java/org/akomantoso/TestAnValidatorTest_CSD06.java#L46-L47) and the [latter should not](https://github.com/kohsah/akomantoso-lib/blob/master/src/test/java/org/akomantoso/TestAnValidatorTest_CSD06.java#L50-L51)? This is not obvious to me.

**Comment by kohsah** [comment]
Hi @lewismc , this is a known issue (see https://github.com/kohsah/akomantoso-lib/issues/14 ). I think its best to have the tests only for the latest AN release (currently CSD14 ... the library is still on CSD13). And also add method checking (not sure if anyone is using the older releases of Akoma Ntoso ? )
